import { ipcMain } from "electron";
import type { LocalDatabase } from "./localDatabase";
import type { SyncEngine } from "./syncEngine";
import { assertLicensedModule, checkLocalLicense } from "./licenseService";
import { printReceipt } from "./receiptPrinter";

export const registerIpcHandlers = (db: LocalDatabase, sync: SyncEngine): void => {
  ipcMain.handle("dashboard:get", () => db.getDashboard());
  ipcMain.handle("products:list", (_event, query) => db.listProducts(query));
  ipcMain.handle("products:save", (_event, product) => db.upsertProduct(product));
  ipcMain.handle("products:stock-movement", (_event, input) => db.adjustProductStock(input));
  ipcMain.handle("products:stock-movements", (_event, productId?: string) => db.listProductStockMovements(productId));
  ipcMain.handle("products:categories", () => db.listCategories());
  ipcMain.handle("products:importCsv", (_event, csv: string) => db.importProductsFromCsv(csv));
  ipcMain.handle("customers:list", (_event, search: string) => db.listCustomers(search));
  ipcMain.handle("customers:save", (_event, customer) => db.upsertCustomer(customer));
  ipcMain.handle("customers:delete", (_event, customerId: string) => db.deleteCustomer(customerId));
  ipcMain.handle("customers:payment", (_event, input) => db.registerCustomerPayment(input.customerId, input.amount));
  ipcMain.handle("customers:open-summary", () => db.getCustomerOpenSummary());
  ipcMain.handle("sales:checkout", (_event, input) => db.checkoutSale(input));
  ipcMain.handle("sales:list", (_event, filters) => db.listSales(filters));
  ipcMain.handle("sales:cancel", (_event, input) =>
    typeof input === "string" ? db.cancelSale(input) : db.cancelSale(input.saleId, { login: input.login, password: input.password, pin: input.pin })
  );
  ipcMain.handle("sales:remove-cancelled", (_event, input) => db.removeCancelledSale(input.saleId, { login: input.login, password: input.password, pin: input.pin }));
  ipcMain.handle("sales:receipt", (_event, saleId: string) => db.getSaleReceiptHtml(saleId));
  ipcMain.handle("cash:current", () => db.getCurrentCashRegister());
  ipcMain.handle("cash:summary", () => db.getCashSummary());
  ipcMain.handle("cash:open", (_event, openingAmount: number) => db.openCashRegister(openingAmount));
  ipcMain.handle("cash:movement", (_event, input) => db.addCashMovement(input.type, input.description, input.amount));
  ipcMain.handle("cash:close", (_event, input) => db.closeCashRegister(input));
  ipcMain.handle("sync:status", () => sync.getStatus());
  ipcMain.handle("sync:flush", () => {
    assertLicensedModule(db, "cloud");
    return sync.flush();
  });
  ipcMain.handle("license:check", () => checkLocalLicense(db));
  ipcMain.handle("auth:state", () => db.getAuthState());
  ipcMain.handle("auth:login", (_event, input) => db.login(input));
  ipcMain.handle("auth:logout", (_event, sessionId?: string) => db.logout(sessionId));
  ipcMain.handle("auth:lock", () => db.lockSession());
  ipcMain.handle("auth:unlock", (_event, input) => db.unlockSession(input));
  ipcMain.handle("auth:switch-operator", (_event, input) => db.switchOperator(input));
  ipcMain.handle("auth:authorize", (_event, input) => db.authorizeCredential(input));
  ipcMain.handle("auth:security-settings", () => db.getAuthState().settings);
  ipcMain.handle("auth:save-security-settings", (_event, input) => db.saveSecuritySettings(input));
  ipcMain.handle("auth:save-user", (_event, input) => db.saveUser(input));
  ipcMain.handle("auth:set-user-active", (_event, input) => db.setUserActive(input.userId, input.active));
  ipcMain.handle("auth:reset-password", (_event, input) => db.resetUserPassword(input.userId, input.password));
  ipcMain.handle("auth:reset-pin", (_event, input) => db.resetUserPin(input.userId, input.pin));
  ipcMain.handle("auth:save-role", (_event, input) => db.saveRole(input));
  ipcMain.handle("auth:duplicate-role", (_event, roleId: string) => db.duplicateRole(roleId));
  ipcMain.handle("auth:set-role-active", (_event, input) => db.setRoleActive(input.roleId, input.active));
  ipcMain.handle("auth:reset-role-defaults", (_event, roleId: string) => db.resetRoleDefaults(roleId));
  ipcMain.handle("system:state", () => db.getSystemState());
  ipcMain.handle("system:activate", (_event, input) => db.activateSystem(input));
  ipcMain.handle("system:settings", (_event, input) => db.updateSettings(input));
  ipcMain.handle("system:cloud", (_event, input) => db.activateCloud(input));
  ipcMain.handle("system:company", (_event, input) => db.updateCompany(input));
  ipcMain.handle("system:manager", (_event, password: string) => db.validateManagerPassword(password));
  ipcMain.handle("system:authorize", (_event, input) => db.authorizeAction(input));
  ipcMain.handle("system:audit", () => db.listAudit());
  ipcMain.handle("system:audit-event", (_event, input) => db.recordAuditEvent(input));
  ipcMain.handle("system:security", () => db.listSecurity());
  ipcMain.handle("system:backup-state", () => db.getBackupState());
  ipcMain.handle("system:backup-export", () => db.exportLocalBackup());
  ipcMain.handle("system:backup-restore", (_event, filePath: string) => db.restoreLocalBackup(filePath));
  ipcMain.handle("pix:config", () => db.getPixConfig());
  ipcMain.handle("pix:save-config", (_event, input) => db.savePixConfig(input));
  ipcMain.handle("pix:create-charge-mock", (_event, input) => db.createPixChargeMock(input.amount, input.saleId));
  ipcMain.handle("pix:charge-status-mock", (_event, chargeId: string) => db.getPixChargeStatusMock(chargeId));
  ipcMain.handle("pix:cancel-charge-mock", (_event, chargeId: string) => db.cancelPixChargeMock(chargeId));
  ipcMain.handle("pix:confirm-charge-mock", (_event, chargeId: string) => db.confirmPixChargeMock(chargeId));
  ipcMain.handle("pix:static-payload", () => db.generateStaticPixQrCodePayload());
  ipcMain.handle("pix:dynamic-payload-mock", (_event, input) => db.generateDynamicPixQrCodeMock(input.amount, input.saleId));
  ipcMain.handle("fiscal:config", () => db.getFiscalConfig());
  ipcMain.handle("fiscal:save-config", (_event, input) => db.saveFiscalConfig(input));
  ipcMain.handle("fiscal:validate-config", () => db.validateFiscalConfig());
  ipcMain.handle("fiscal:issue-nfce-mock", (_event, saleId: string) => db.issueNfceMock(saleId));
  ipcMain.handle("fiscal:cancel-document-mock", (_event, documentId: string) => db.cancelFiscalDocumentMock(documentId));
  ipcMain.handle("fiscal:status-mock", (_event, documentId: string) => db.getFiscalStatusMock(documentId));
  ipcMain.handle("receipt:print", (_event, html: string) => printReceipt(html));
};
